---
name: "Build"

permissions: {}

on:
  workflow_call:

jobs:
  build:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false

      - uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: false
          cache-dependency-glob: "pyproject.toml"

      - name: "Check for existing dist/ directory"
        run: |
          if test -e dist
          then
            echo "a pre-existing dist directory was detected >&2"
            exit 1
          fi

      - name: "Build sdist and wheel"
        id: "build"
        run: |
          uv build --sdist --wheel

      - name: "Upload dists to build artifacts"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"  # v4.6.2
        with:
          name: "distributions"
          path: "dist/*"
          if-no-files-found: "error"
          compression-level: 0  # dists are already compressed
...
