---
name: "Linting & Tests"

permissions: {}

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  package-lint:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false
      - name: "Install uv"
        uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: "Run package lints"
        run: >
          uv tool run
          --python '${{ matrix.python-version }}'
          --constraints constraints-ci.txt
          --with tox-uv
          tox run -e manifest,pyroma
  code-lint:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false
      - name: "Install uv"
        uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: "Run code lints"
        run: >
          uv tool run
          --python '${{ matrix.python-version }}'
          --constraints constraints-ci.txt
          --with tox-uv
          tox run -e ruff,mypy,pydoclint,docstr-coverage
  doc-lint:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]  # remove 3.9 since Sphinx no longer supports it
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false
      - name: "Install uv"
        uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: "Run documentation lints"
        run: >
          uv tool run
          --python '${{ matrix.python-version }}'
          --constraints constraints-ci.txt
          --with tox-uv
          tox run -e doc8,docs
  test:
    permissions:
      contents: "read"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - uses: "actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871"  # v4.2.1
        with:
          persist-credentials: false
      - name: "Install uv"
        uses: "astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086"  # v3.1.5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: "Run tests"
        run: >
          uv tool run
          --python '${{ matrix.python-version }}'
          --constraints constraints-ci.txt
          --with tox-uv
          tox run -e coverage-clean,py,coverage-report
      - uses: "codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574"  # v5.4.0
        with:
          disable_search: true
          disable_telem: true
          fail_ci_if_error: true
          files: "coverage.xml"
          token: "${{ secrets.CODECOV_TOKEN }}"
...
